version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_server'
    hostname: 'rabbitmq'
    env_file:
      - .env
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - rabbitmq_net

  worker:
    build:
      context: .
      dockerfile: "./worker.Dockerfile"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - rabbitmq_net

  http_api:
    build:
      context: .
      dockerfile: "./api.Dockerfile"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    networks:
      - rabbitmq_net



  websocket_api:
    build:
      context: .
      dockerfile: "./websocket.Dockerfile"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - "8001:8001"
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
